### ISSUE TITLE
Please outline requirements on how to migrate from J2ObjC -> J2ObjC-framework

### ISSUE THREAD

**Issue by haxwagon** [actorapp/J2ObjC-Framework#1]
this project is a really good idea but can you please provide some more flavor in:
"""
Unfortunatelly, this library doesn't compatable with original one in terms that there are different include paths in generated sources.

All inlcude/import with quotes was replaced with andgled/frameworked version.
"""

The generated j2objc code still has lots of 
# import "IOSClass.h"

Do we need to manually patch these out of code to either:
@import j2objc;

or 
# import <IOSClass.h>

Thanks!

**Comment by ex3ndr** [comment]
Yes, i have implemented small python script: https://github.com/actorapp/actor-platform/blob/master/actor-sdk/sdk-core-ios/preprocess.py
That replaces imports
